config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources :tasks
  resources :skills
  resources :locations
  resources :tasks
  resources :events
  resources :programs

  get 'welcome/index'

  root 'welcome#index'
end

app/models/event.rb
class Event < ActiveRecord::Base
end

app/models/location.rb
class Location < ActiveRecord::Base
  #has_one :manager, :class_name => 'User'
end

app/models/program.rb
class Program < ActiveRecord::Base
  has_many  :volunteers, :class_name => 'User', through: :programs_users
  has_many :programs_users
  accepts_nested_attributes_for :volunteers
end

app/models/programs_users.rb
class ProgramsUsers < ActiveRecord::Base
  belongs_to :user
  belongs_to :program
end

app/models/skill.rb
class Skill < ActiveRecord::Base
end

app/models/task.rb
class Task < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :programs, :class_name => 'Program', through: :programs_users
  has_many :programs_users
  accepts_nested_attributes_for :programs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index
    @events = Event.all
  end

  def new
    @event = Event.new
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])

    if @event.update(event_params)
      flash[:notice] = "Event Sucessfully Updated"
    else
      flash[:notice] = "Error Updating Event"
    end

    redirect_to action: 'edit'
  end

  def create
    @event = Event.new(event_params)

    if @event.save
      redirect_to @event
    else
      render 'new'
    end
  end

  def show
    @event = Event.find(params[:id])
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    redirect_to events_path
  end

  private
    def event_params
      params.require(:event).permit(:name, :email, :phone, :address, :is_admin, :is_volunteer)
    end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  def index
    @locations = Location.all
  end

  def new
    @location = Location.new
  end

  def edit
    @location = Location.find(params[:id])
    @managers_array = User.where(is_admin: true).pluck(:name, :id)
  end

  def update
    @location = Location.find(params[:id])

    if @location.update(location_params)
      flash[:notice] = "Location Sucessfully Updated"
    else
      flash[:notice] = "Error Updating Location"
    end

    redirect_to action: 'edit'
  end

  def create
    @location = Location.new(location_params)

    if @location.save
      redirect_to @location
    else
      render 'new'
    end
  end

  def show
    @location = Location.find(params[:id])
    @managers_array = User.where(is_admin: true).pluck(:name, :id)
  end

  def destroy
    @location = Location.find(params[:id])
    @location.destroy

    redirect_to locations_path
  end

  private
    def location_params
      params.require(:location).permit(:suburb, :state, :address, :manager, :phone)
    end

end

app/controllers/programs_controller.rb
class ProgramsController < ApplicationController

  def index
    @programs = Program.all
  end

  def new
    @program = Program.new
  end

  def edit
    @program = Program.find(params[:id])
  end

  def update
    @program = Program.find(params[:id])

    if @program.update(program_params)
      flash[:notice] = "Program Sucessfully Updated"
    else
      flash[:notice] = "Error Updating Program"
    end

    redirect_to action: 'edit'
  end

  def create
    @program = Program.new(program_params)

    if @program.save
      redirect_to @program
    else
      render 'new'
    end
  end

  def show
    @program = Program.find(params[:id])
  end

  def destroy
    @program = Program.find(params[:id])
    @program.destroy

    redirect_to programs_path
  end

  private
    def program_params
      params.require(:program).permit(:name, :coordinator, :description, :active)
    end

end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  def index
    @skills = Skill.all
  end

  def new
    @skill = Skill.new
  end

  def edit
    @skill = Skill.find(params[:id])
  end

  def update
    @skill = Skill.find(params[:id])

    if @skill.update(skill_params)
      redirect_to @skill
    else
      render 'edit'
    end
  end

  def create
    @skill = Skill.new(skill_params)

    if @skill.save
      redirect_to @skill
    else
      render 'new'
    end
  end

  def show
    @skill = Skill.find(params[:id])
  end

  def destroy
    @skill = Skill.find(params[:id])
    @skill.destroy

    redirect_to skills_path
  end

  private
    def skill_params
      params.require(:skill).permit(:name, :email)
    end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @tasks = Task.all
  end

  def new
    @task = Task.new
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])

    if @task.update(task_params)
      flash[:notice] = "Task Sucessfully Updated"
    else
      flash[:notice] = "Error Updating Task"
    end

    redirect_to action: 'edit'
  end

  def create
    @task = Task.new(task_params)

    if @task.save
      redirect_to @task
    else
      render 'new'
    end
  end

  def show
    @task = Task.find(params[:id])
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    redirect_to tasks_path
  end

  private
    def task_params
      params.require(:task).permit(:name, :email, :phone, :address, :is_admin, :is_volunteer)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  require 'pry'

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update

    @user = User.find(params[:id])

    binding.pry

    #params[:programs_attributes].each do |p|

    #end



    if @user.update(user_params)
      flash[:notice] = "User Sucessfully Updated"
    else
      flash[:notice] = "Error Updating User"
    end

    redirect_to action: 'edit'
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to @user
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    redirect_to users_path
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :phone, :address, :is_admin, :is_volunteer, programs_attributes: [:id, :_destroy])
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @message = "welcome to the Welcome To Australia volunteer management system"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/programs_helper.rb
module ProgramsHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/events/_form.html.erb
<%= form_for @program do |f| %>
  <% if @program.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@program.errors.count, "error") %> prohibited
        this user from being saved:
      </h2>
      <ul>
        <% @program.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <ul class="nav nav-tabs" role="tablist">
    <li role="presentation" class="active"><a href="#main" aria-controls="main" role="tab" data-toggle="tab">Main</a></li>
    <li role="presentation"><a href="#schedule" aria-controls="schedule" role="tab" data-toggle="tab">Schedule</a></li>
  </ul>

  <div id="main-container" class="container"><br>
    <div class="tab-content">
      <div role="tabpanel" class="tab-pane active" id="main">
        <div class="row">
          <div class="col-xs-1 text-right">
            <%= f.label :name %>
          </div>

          <div class="col-xs-3 edit">
            <%= f.text_field :name %>
          </div>

          <div class="col-xs-1 text-right">
            <%= f.label :admin %>
          </div>

          <div class="col-xs-3 edit">
            <%= f.check_box :is_admin %>
          </div>
        </div>

        <div class="row">
          <div class="col-xs-1 text-right">
            <%= f.label :phone %>
          </div>

          <div class="col-xs-3 edit">
            <%= f.text_field :phone %>
          </div>

          <div class="col-xs-1 text-right">
            <%= f.label :volunteer %>
          </div>

          <div class="col-xs-3 edit">
            <%= f.check_box :is_volunteer %>
          </div>
        </div>

        <div class="row">
          <div class="col-xs-1 text-right">
            <%= f.label :email %><br>
          </div>

          <div class="col-xs-3 edit">
            <%= f.text_field :email %>
          </div>
        </div>

        <div class="row">
          <div class="col-xs-1 text-right">
            <%= f.label :address %>
          </div>

          <div class="col-xs-3 edit">
            <%= f.text_area :address %>
          </div>
        </div>
      </div>

      <div role="tabpanel" class="tab-pane" id="volunteers">
        <p> list of volunteers recruited </p>
      </div>
    </div>
  </div>

  <script type="text/javascript">
    $('#nav-tabs a').click(function (e) {
      e.preventDefault()
      $(this).tab('show')
    })
  </script>

<% end %>

app/views/events/index.html.erb
<div class="row">
  <div class="col-xs-6">
    <h1>Events</h1>
  </div>

  <div class="col-xs-1">
    <%= link_to 'New Event', new_event_path, class:"btn btn-default" %>
  </div>
</div>

<div id="main-container" class="container">
  <div class="row">
    <div class="col-xs-3">
      <h3>Name</h3>
    </div>

    <div class="col-xs-2">
      <h3>Coordinator</h3>
    </div>

    <div class="col-xs-2">
      <h3>Start</h3>
    </div>

    <div class="col-xs-2">
      <h3>Finish</h3>
    </div>
  </div>

  <% @events.each do |event| %>
    <div class="row">
      <div class="col-xs-3"><%= event.name %></div>
      <div class="col-xs-2"><%= event.coordinator %></div>
      <div class="col-xs-2"><%= event.start_date %></div>
      <div class="col-xs-2"><%= event.end_date %></div>
      <div class="col-xs-1"><%= link_to 'Show', event_path(event), class:"btn btn-default" %></div>
      <div class="col-xs-1"><%= link_to 'Edit', edit_event_path(event), class:"btn btn-default" %></div>
      <div class="col-xs-1"><%= link_to 'Delete', event_path(event), class:"btn btn-default",
              method: :delete,
              data: { confirm: 'for real yo?' } %></div>
    </div>
  <% end %>
</div>

<script type="text/javascript">
  $('#nav-tabs a').click(function (e) {
    e.preventDefault()
    $(this).tab('show')
  })
</script>

app/views/locations/_form.html.erb
<%= form_for @location do |f| %>
  <% if @location.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@location.errors.count, "error") %> prohibited
        this location from being saved:
      </h2>
      <ul>
        <% @location.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div id="main-container" class="container">
    <ul class="nav nav-tabs" role="tablist">
      <li role="presentation" class="active"><a href="#main" aria-controls="main" role="tab" data-toggle="tab">Main</a></li>
      <li role="presentation"><a href="#volunteers" aria-controls="volunteers" role="tab" data-toggle="tab">Volunteers</a></li>
    </ul>

    <div class="tab-content">
      <div role="tabpanel" class="tab-pane active" id="main">
        <div class="row">
          <div class="col-xs-1 text-right">
            <%= f.label :state %>
          </div>

          <div class="col-xs-2 edit">
            <%= f.text_field :state %>
          </div>

          <div class="col-xs-1 text-right">
            <%= f.label :address %>
          </div>

          <div class="col-xs-2 edit">
            <%= f.text_field :address %>
          </div>
        </div>

        <div class="row">
          <div class="col-xs-1 text-right">
            <%= f.label :manager %>
          </div>

          <div class="col-xs-2 edit">
            <%= f.select(:manager, options_for_select(@managers_array, @location.manager), include_blank: true) %>
          </div>

          <div class="col-xs-1 text-right">
            <%= f.label :suburb %>
          </div>

          <div class="col-xs-2 edit">
            <%= f.text_field :suburb %>
          </div>
        </div>

        <div class="row">
          <div class="col-xs-1 text-right">
            <%= f.label :phone %><br>
          </div>

          <div class="col-xs-2 edit">
            <%= f.text_field :phone %>
          </div>
        </div>
      </div>

      <div role="tabpanel" class="tab-pane" id="volunteers">
        <p> here is the second tab </p>
      </div>
    </div>
  </div>

  <script type="text/javascript">
    $('#nav-tabs a').click(function (e) {
      e.preventDefault()
      $(this).tab('show')
    })
  </script>
<% end %>

app/views/locations/edit.html.erb
<% if flash[:notice] %>
  <div class="row">
    <div class="label label-success col-xs-offset-4 col-xs-4">
      <%= flash[:notice] %>
    </div>
  </div>
<% end %>

<div class= "container">
  <div class= "row">
    <div class="col-xs-6">
      <h2>Editing Location: <%= @location.suburb%></h2>
    </div>

    <div class="col-xs-1">
      <%= link_to 'Back', locations_path, class:"btn btn-default" %>
    </div>

    <div class="col-xs-1">
      <input type="submit" value="save" class="btn btn-default" name="commit" form="edit_location_<%= @location.id%>"></input>
    </div>
  </div>
</div>

<%= render 'form' %>

app/views/locations/index.html.erb
<div id="main-container" class="container">
  <div class="row">
    <div class="col-xs-6">
      <h1>Locations</h1>
    </div>

    <div class="col-xs-1">
      <%= link_to 'New Location', new_location_path, class:"btn btn-default" %>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-1">
      <h3>State</h3>
    </div>

    <div class="col-xs-3">
      <h3>Address</h3>
    </div>

    <div class="col-xs-3">
      <h3>Manager</h3>
    </div>
  </div>

  <% @locations.each do |location| %>
    <div class="row">
      <div class="col-xs-1"><%= location.state %></div>
      <div class="col-xs-3"><%= location.address %></div>
      <div class="col-xs-3"><%= User.find_by_id(location.manager).name %></div>
      <div class="col-xs-1"><%= link_to 'Show', location_path(location), class:"btn btn-default" %></div>
      <div class="col-xs-1"><%= link_to 'Edit', edit_location_path(location), class:"btn btn-default" %></div>
      <div class="col-xs-1"><%= link_to 'Delete', location_path(location), class:"btn btn-default",
              method: :delete,
              data: { confirm: 'for real yo?' } %></div>
    </div>
  <% end %>
</div>

<script type="text/javascript">
  $('#nav-tabs a').click(function (e) {
    e.preventDefault()
    $(this).tab('show')
  })
</script>

app/views/locations/new.html.erb
<div class= "row">
  <div class="col-xs-6">
    <h1>New Location</h1>
  </div>

  <div class="col-xs-1">
    <%= link_to 'Back', locations_path, class:"btn btn-default" %>
  </div>

  <div class="col-xs-1">
    <input type="submit" value="save" class="btn btn-default" name="commit" form="new_location"></input>
  </div>
</div>

<%= render 'form' %>

app/views/locations/show.html.erb
<div class= "row">
  <div class="col-xs-6">
    <h2>Location: <%= @location.suburb%></h2>
  </div>

  <div class="col-xs-1">
    <%= link_to 'Back', locations_path, class:"btn btn-default" %>
  </div>

  <div class="col-xs-1">
    <%= link_to 'Edit', edit_location_path(@location), class:"btn btn-default" %>
  </div>
</div>

<%= render 'form' %>

app/views/programs/_form.html.erb
<%= form_for @program do |f| %>
  <% if @program.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@program.errors.count, "error") %> prohibited
        this user from being saved:
      </h2>
      <ul>
        <% @program.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div id="main-container" class="container"><br>
    <ul class="nav nav-tabs" role="tablist">
      <li role="presentation" class="active"><a href="#main" aria-controls="main" role="tab" data-toggle="tab">Main</a></li>
      <li role="presentation"><a href="#volunteers" aria-controls="volunteers" role="tab" data-toggle="tab">Volunteers</a></li>
    </ul>

    <div class="tab-content">
      <div role="tabpanel" class="tab-pane active" id="main">
        <div class="row">
          <div class="col-xs-1 text-right">
            <%= f.label :name %>
          </div>

          <div class="col-xs-3 edit">
            <%= f.text_field :name %>
          </div>

          <div class="col-xs-1 text-right">
            <%= f.label :manager %>
          </div>

          <div class="col-xs-3 edit">
            <%= f.select(:coordinator, options_for_select(User.all.pluck(:name,:id), @program.coordinator), include_blank: true) %>
          </div>
        </div>

        <div class="row">
          <div class="col-xs-1 text-right">
            <%= f.label :description %>
          </div>

          <div class="col-xs-3 edit">
            <%= f.text_area :description %>
          </div>


          <div class="col-xs-1 text-right">
            <%= f.label :active %>
          </div>

          <div class="col-xs-1 edit">
            <%= f.check_box :active %>
          </div>
        </div>
      </div>

      <div role="tabpanel" class="tab-pane" id="volunteers">
        <% @program.volunteers.each do |user| %>
          <div class="row">
            <div class="col-xs-3"><%= user.name %></div>
            <div class="col-xs-3"><%= user.is_admin %></div>
            <div class="col-xs-1"><%= link_to 'Show', user_path(user), class:"btn btn-default" %></div>
            <div class="col-xs-1"><%= link_to 'Edit', edit_user_path(user), class:"btn btn-default" %></div>
            <div class="col-xs-1"><%= link_to 'Delete', user_path(user), class:"btn btn-default",
                    method: :delete,
                    data: { confirm: 'for real yo?' } %></div>
          </div>

        <% end %>
      </div>
    </div>
  </div>

  <script type="text/javascript">
    $('#nav-tabs a').click(function (e) {
      e.preventDefault()
      $(this).tab('show')
    })
  </script>

<% end %>

app/views/programs/edit.html.erb
<% if flash[:notice] %>
  <div class="row">
    <div class="label label-success col-xs-offset-4 col-xs-4">
      <%= flash[:notice] %>
    </div>
  </div>
<% end %>

<div class="container">
  <div class="row">
    <div class="col-xs-6">
      <h2>Editing Program: <%= @program.name%></h2>
    </div>

    <div class="col-xs-1">
      <%= link_to 'Back', programs_path, class:"btn btn-default" %>
    </div>

    <div class="col-xs-1">
      <input type="submit" value="save" class="btn btn-default" name="commit" form="edit_program_<%= @program.id%>"></input>
    </div>
  </div>
</div>

<%= render 'form' %>

app/views/programs/index.html.erb
<div id="main-container" class="container">
  <div class="row">
    <div class="col-xs-6">
      <h1>Programs</h1>
    </div>

    <div class="col-xs-1">
      <%= link_to 'New Program', new_program_path, class:"btn btn-default" %>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-3">
      <h3>Name</h3>
    </div>

    <div class="col-xs-3">
      <h3>Coordinator</h3>
    </div>
  </div>

  <% @programs.each do |program| %>
    <% @name = User.find_by_id(program.coordinator) %>
    <% @name = @name ? @name.name : "" %>
    <div class="row">
      <div class="col-xs-3"><%= program.name %></div>
      <div class="col-xs-3"><%= @name %></div>
      <div class="col-xs-1"><%= link_to 'Show', program_path(program), class:"btn btn-default" %></div>
      <div class="col-xs-1"><%= link_to 'Edit', edit_program_path(program), class:"btn btn-default" %></div>
      <div class="col-xs-1"><%= link_to 'Delete', program_path(program), class:"btn btn-default",
              method: :delete,
              data: { confirm: 'for real yo?' } %></div>
    </div>
  <% end %>
</div>

<script type="text/javascript">
  $('#nav-tabs a').click(function (e) {
    e.preventDefault()
    $(this).tab('show')
  })
</script>

app/views/programs/new.html.erb
<div class="row">
  <div class="col-xs-6">
    <h1>New Program</h1>
  </div>

  <div class="col-xs-1">
    <%= link_to 'Back', programs_path, class:"btn btn-default" %>
  </div>

  <div class="col-xs-1">
    <input type="submit" value="save" class="btn btn-default" name="commit" form="new_program"></input>
  </div>
</div>

<%= render 'form' %>

app/views/programs/show.html.erb
<div class="row">
  <div class="col-xs-6">
    <h2>Program: <%= @program.name%></h2>
  </div>

  <div class="col-xs-1">
    <%= link_to 'Back', programs_path, class:"btn btn-default" %>
  </div>

  <div class="col-xs-1">
    <%= link_to 'Edit', edit_program_path(@program), class:"btn btn-default" %>
  </div>
</div>

<%= render 'form' %>

<script type="text/javascript">
  $(".edit>input,.edit>textarea").attr('disabled','disabled');
</script>

app/views/skills/index.html.erb
<div class="row">
  <div class="col-xs-6">
    <h1>Skills</h1>
  </div>

  <div class="col-xs-1">
    <%= link_to 'New Skill', new_skill_path, class:"btn btn-default" %>
  </div>
</div>

<div id="main-container" class="container">
  <div class="row">
    <div class="col-xs-3">
      <h3>Name</h3>
    </div>
  </div>

  <% @skills.each do |skill| %>
    <div class="row">
      <div class="col-xs-3"><%= skill.name %></div>
      <div class="col-xs-1"><%= link_to 'Show', skill_path(skill), class:"btn btn-default" %></div>
      <div class="col-xs-1"><%= link_to 'Edit', edit_skill_path(skill), class:"btn btn-default" %></div>
      <div class="col-xs-1"><%= link_to 'Delete', skill_path(skill), class:"btn btn-default",
              method: :delete,
              data: { confirm: 'for real yo?' } %></div>
    </div>
  <% end %>
</div>

<script type="text/javascript">
  $('#nav-tabs a').click(function (e) {
    e.preventDefault()
    $(this).tab('show')
  })
</script>

app/views/tasks/index.html.erb
<div class="row">
  <div class="col-xs-6">
    <h1>Tasks</h1>
  </div>

  <div class="col-xs-1">
    <%= link_to 'New Task', new_user_path, class:"btn btn-default" %>
  </div>
</div>

<div id="main-container" class="container">
  <div class="row">
    <div class="col-xs-3">
      <h3>Name</h3>
    </div>

    <div class="col-xs-3">
      <h3>Email</h3>
    </div>
  </div>

  <% @tasks.each do |task| %>
    <div class="row">
      <div class="col-xs-3"><%= task.name %></div>
      <div class="col-xs-3"><%= task.email %></div>
      <div class="col-xs-1"><%= link_to 'Show', task_path(task), class:"btn btn-default" %></div>
      <div class="col-xs-1"><%= link_to 'Edit', edit_task_path(task), class:"btn btn-default" %></div>
      <div class="col-xs-1"><%= link_to 'Delete', task_path(task), class:"btn btn-default",
              method: :delete,
              data: { confirm: 'for real yo?' } %></div>
    </div>
  <% end %>
</div>

<script type="text/javascript">
  $('#nav-tabs a').click(function (e) {
    e.preventDefault()
    $(this).tab('show')
  })
</script>

app/views/users/edit.html.erb
<% if flash[:notice] %>
  <div class="row">
    <div class="label label-success col-xs-offset-4 col-xs-4">
      <%= flash[:notice] %>
    </div>
  </div>
<% end %>

<div class= "container">
  <div class="row">
    <div class="col-xs-6">
      <h2>Editing User: <%= @user.name%></h2>
    </div>

    <div class="col-xs-1">
      <%= link_to 'Back', users_path, class:"btn btn-default" %>
    </div>

    <div class="col-xs-1">
      <input type="submit" value="save" class="btn btn-default" name="commit" form="edit_user_<%= @user.id%>"></input>
    </div>
  </div>
</div>

<%= render 'form' %>

app/views/users/index.html.erb
<div id="main-container" class="container">
  <div class="row">
    <div class="col-xs-6">
      <h1>Users</h1>
    </div>

    <div class="col-xs-1">
      <%= link_to 'Add Program', new_user_path, class:"btn btn-default" %>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-3">
      <h3>Name</h3>
    </div>

    <div class="col-xs-3">
      <h3>Email</h3>
    </div>
  </div>

  <% @users.each do |user| %>
    <div class="row">
      <div class="col-xs-3"><%= user.name %></div>
      <div class="col-xs-3"><%= user.email %></div>
      <div class="col-xs-1"><%= link_to 'Show', user_path(user), class:"btn btn-default" %></div>
      <div class="col-xs-1"><%= link_to 'Edit', edit_user_path(user), class:"btn btn-default" %></div>
      <div class="col-xs-1"><%= link_to 'Delete', user_path(user), class:"btn btn-default",
              method: :delete,
              data: { confirm: 'for real yo?' } %></div>
    </div>
  <% end %>
</div>

<script type="text/javascript">
  $('#nav-tabs a').click(function (e) {
    e.preventDefault()
    $(this).tab('show')
  })
</script>

app/views/users/new.html.erb
<div class="row">
  <div class="col-xs-6">
    <h1>New User</h1>
  </div>

  <div class="col-xs-1">
    <%= link_to 'Back', users_path, class:"btn btn-default" %>
  </div>

  <div class="col-xs-1">
    <input type="submit" value="save" class="btn btn-default" name="commit" form="new_user"></input>
  </div>
</div>

<%= render 'form' %>

app/views/users/show.html.erb
<div class="row">
  <div class="col-xs-6">
    <h2>User: <%= @user.name%></h2>
  </div>

  <div class="col-xs-1">
    <%= link_to 'Back', users_path, class:"btn btn-default" %>
  </div>

  <div class="col-xs-1">
    <%= link_to 'Edit', edit_user_path(@user), class:"btn btn-default" %>
  </div>
</div>

<%= render 'form' %>

<script type="text/javascript">
  $(".edit>input,.edit>textarea").attr('disabled','disabled');
</script>